# Generated by Django 3.1.7 on 2021-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsURL',
            fields=[
                ('sports', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('sheet', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sportsurl',
            },
        ),
    ]
